### ISSUE TITLE
NX: Vue Support

### ISSUE THREAD

**Issue by Jordan-Hall** [nrwl/nx#1541]
# Vue Support

With Vue being the next major framework for the frontend and growing. Nx should start supporting Vue.  I'm happy to help support Vue, so I've outlined some expected issues and consideration.

## Expected Issues

Unlike currently supported frameworks. Vue isn't opinionated and allows more control to the developers. View also supports different ways of working, support for .ts files should be relatively straight forward but support for .vue may take longer.

## Considerations

- Should we add support for using Vue using babel?
- Vue supports TSX, should this be included on the first release
- Vue is undergoing a restructure for Vue 3. Should we wait until Vue 3 is officially released? 

## To-Do

- [ ]  Create Vue implementation roadmap
- [ ]  Add support for using Vue with typescript
- [ ]  Add support for using Vue with Vue
- [ ] Create Schematics for both ts and Vue files 
- [ ]  Documentation for Vue support

**Comment by danieldanielecki** [comment]
Great idea! We have Angular, React, Web Component, only Vue.js is missing. Can't wait for this, it should be a priority definitely!

**Comment by Jordan-Hall** [comment]
Hey, just working on Storybook build then this is the priority for me.  Please bear with me, the full support with .vue will have to be added later.

**Comment by jaysoo** [comment]
@Jordan-Hall Great idea.

> Should we add support for using Vue using babel?

Is babel  usage common with Vue? I've seen some setup using just ts-loader. I'm just curious since I've never worked on a production Vue app.

Also note that we're looking to make babel support better. Right now it exists as a React-specific plugin.

**Comment by leonlafa** [comment]
> Hey, just working on Storybook build then this is the priority for me. Please bear with me, the full support with .vue will have to be added later.

Any ETA on this @Jordan-Hall, the community is eagerly awaiting 😀

**Comment by mmelvin0581** [comment]
Would LOVE this!. This is exactly what my company needs right now!!

**Comment by vsavkin** [comment]
@Jordan-Hall let me know if you need any help with this. We are happy to help.

**Comment by Jordan-Hall** [comment]
Now Storybook been merged in my focus is on the vue integration.  Sorry for the delay

**Comment by merlosy** [comment]
Hi @Jordan-Hall ! 
Thank you for taking the time to work on this. Do you have an ETA regarding support for vue? And since vue 3 is almost out, what is your targetted version?

**Comment by Jordan-Hall** [comment]
@merlosy  working slowly on it. Waiting for vue 3 before this carries on

**Comment by satishbabariya** [comment]
@Jordan-Hall https://github.com/vuejs/vue-next aka Vue 3 is totally rewritten in typescript. mostly for the ts support reason. and vue 3 is also backward compatible.
so are you guys going with vue 3 alpha or vue 2?

**Comment by asherccohen** [comment]
Surely this will be very appreciated.

**Comment by Jordan-Hall** [comment]
vue 3 alpha!

**Comment by JamesCoonce** [comment]
How can I help out? I've got a ton of free time!

**Comment by Jordan-Hall** [comment]
Hi @JamesCoonce  I'll push a fork up after the new year. I could do with help :)

**Comment by asherccohen** [comment]
Hi everyone!are there any news for vue.js support, I heard it's in alpha stage.

**Comment by Jordan-Hall** [comment]
Working on it. Only in the evenings but on Limited internet as Im working away. Aiming for it to be ready. Just after vue release

**Comment by vsavkin** [comment]
Hey folks! Just wanted to let you know that 8.12 release will come with some tooling to make writing, and, most importantly, testing Nx plugins much easier. We should have it out next week.

**Comment by puku0x** [comment]
Does `create-nx-plugin` help us to make a builder for Vue.js project?
https://blog.nrwl.io/nx-8-12-distributed-caching-improved-dependency-detection-better-support-for-buildable-libraries-6f7cec17b83f

**Comment by Jordan-Hall** [comment]
@pesoklp13 I'm going to take a look at it tonight. I've helped on the storybook builder so that part i'm fine. Just had poor internet and will still be poor until the 8 but dont worry im still working on it :)

**Comment by jaysoo** [comment]
@puku0x @Jordan-Hall That's exactly why we created the `create-nx-plugin` package. :)

We can't accept everything into the main repo because doing so means we have to have the necessary resources to maintain it. In the future we can start promoting third-party plugins if they cover stacks that we don't cover.

**Comment by wickstargazer** [comment]
@jaysoo Hi, what kind of things would you be looking into to promote a third-party plugin, is there a guideline? As we are developing some infra as a code plugins for nx and using it in production, we would like to help contribute so the eco-system becomes better :)

**Comment by Jordan-Hall** [comment]
@jaysoo if thats the case. Should we create a community repo for 3rd party plugins with some core maintainers

**Comment by vsavkin** [comment]
We are working on good docs for `create-nx-plugin` now. Stay tuned :)

After that, we are planing to create a page on `nx.dev` with high-quality Nx plugins. And then at some point in the future integrate them into `nx list`.

We are happy to help with third-party plugin issues on case-by-case basis. E.g., if you have any questions, open issues and we will help you out.

**Comment by asherccohen** [comment]
Awesome @vsavkin! I will create a plugin for React native as soon as your tool is ready!

**Comment by minhlucvan** [comment]
Hi guys, how are things going? I'm very interest in this feature so if have anything that I can help just ping me :)

**Comment by jdpearce** [comment]
@asherccohen We are already working on a React native plugin! (I believe @jaysoo is working on that at the moment)

**Comment by asherccohen** [comment]
@jdpearce great news!per me know of help is needed!

**Comment by Jordan-Hall** [comment]
@minhlucvan  I'll set up a slack channel in coming days. Build coming on almost sorted (including for libs)

**Comment by jaysoo** [comment]
Hey All, the Nx plugin support has been launched. https://nx.dev/nx-plugins

Community plugin guide is available here: https://nx.dev/react/guides/nx-plugin

We won't be adding Vue support in the main repo, but if someone wants to help with a Community plugin feel free to reach out to us.

**Comment by asherccohen** [comment]
Hey guys. Has anyone been working on this?I heard progress is good, worth releasing as a community plugin. Where's the repo so we can contribute?

**Comment by BuckyMaler** [comment]
I opened a [draft PR](https://github.com/ZachJW34/nx-plus/pull/18) adding Vue 2 support to Nx. The work is early. A borderline proof of concept. Hence, it being a **draft** PR. 😄 

This is a weeks worth of after hours work. I was able to leverage Vue CLI for the dev server and production build, but I'm questioning whether I should continue leveraging Vue CLI or switch to Nx's `@nrwl/web` package.

Again, this work is for Vue 2 and is very early, but I wanted to share in progress work that you can track.

**Comment by asherccohen** [comment]
Can't wait to see it in action!

**Comment by BuckyMaler** [comment]
@ZachJW34 and I have made good progress on this. We hope to have a pre-release published by the end of the month.

**What you can expect:**
- An app schematic with various options (e.g. routing and CSS pre-processors)
- Lint, test, e2e, serve, and build targets for your apps
- A Vuex schematic for adding Vuex to an existing app
- TypeScript support (no JS support 😬 )
- Maybe more 🤔 

We'll also try to have documentation and issues created for those who are interested in contributing. It would be greatly appreciated. 😄 

You can track progress [here](https://github.com/ZachJW34/nx-plus).

**Comment by BuckyMaler** [comment]
We released v0.2.0 of Nx + Vue! First class support for Vue in your Nx workspace. [Check it out!](https://github.com/ZachJW34/nx-plus/tree/master/libs/vue#readme) 📣 

There was no announcement about v0.1.0 because you wouldn't like it. We didn't like it. We changed the DX quite a bit in v0.2.0. If you like Vue CLI you'll feel right at home. ✌️

**Comment by sg1asgard** [comment]
Hi,
Maybe have a support for Nuxt as well such as this module?
https://github.com/edbzn/nx-nuxt

Bests,
George

**Comment by iamandrewluca** [comment]
@sg1asgard https://github.com/ZachJW34/nx-plus/tree/master/libs/nuxt

**Comment by stewones** [comment]
I can’t believe there’s no official support for Vue but is there for React 🙄

**Comment by nathandaly** [comment]
Can we please get official Vue support (possibly with Vite). I am currently only keeping the backend services in NX when I would like to keep it all together :)

**Comment by samatechtw** [comment]
I'm putting together a Vue3/Vite plugin here: https://github.com/samatechtw/nx-vue3-vite

We use it internally, but I wouldn't recommend it for production yet. There are still a few kinks to work out, and it's not well tested.

**Comment by wind4gis** [comment]
emm...there are still a lot of people using vue2...how about support vue2 also?

**Comment by npwork** [comment]
Please add native support for vue 2 and 3.

**Comment by Jordan-Hall** [comment]
Guys if you want this, you could use NX vite plugin and then inside the vite.config.js file add the required plugin for vue

**Comment by mohsinamjad** [comment]
+1,  need official production level support for vue.

**Comment by maxigimenez** [comment]
We are moving to a monorepo solution and sadly we cannot use NX because of the lacking of Vue support 😭

**Comment by martinstanojevic** [comment]
+1 for Vue3 support.

**Comment by dakt** [comment]
Woah, I have to ditch NX because of lacking support for Vue.

**Comment by jcmillett** [comment]
I agree with everyone else, official vue support is a must for adopting nx. The community provided nx-plus/vue package doesn't appear to be actively maintained. It also requires using nx 12, which is almost 6 months old at this point. Using nx 12 also means that it's not possible to use certain plugins, like @nrwl/js since it's only available for nx 13.

**Comment by dakt** [comment]
> It's literally awful that Nx doesn't support Vue. Any other monorepo solutions that one can try for Vue?

We went for Turborepo and it's quite good. It's framework agnostic so no problem there.

**Comment by amitvchaudhary** [comment]
@dakt Yes I have started using it but I am facing problems in creating shared component library which depends on another third-party component library. In case you have any good material to refer, please let me know.

**Comment by TrayHard** [comment]
Please add Vue support!

**Comment by ryan-buckman** [comment]
Would love to see Vue support!

**Comment by realityfilter** [comment]
There is another one: https://nxext.dev vue support via vite.

**Comment by duke-git** [comment]
I can't believe that Nx doesn't support Vue.js!

**Comment by troncali** [comment]
Here's an example monorepo with the standard Vue 3 scaffold using Vite and Vitest: [troncali/nest-vue](https://github.com/troncali/nest-vue).  The demo is at [nest-vue.troncali.com](https://nest-vue.troncali.com/).

This may be a naive implementation, but using Nx's `run-commands` executor with `vite` and `vitest` seems to work well, caching included.  I didn't use the plugins because they didn't seem to support all of what Vite/Vitest could do, and they seemed to just call the underlying CLIs anyway.

I think the configurations that matter are [`workspace.json`](https://github.com/troncali/nest-vue/blob/1a8cc12da5a8bbf3091180baa7784b73c88cb454/workspace.json#L824-L918) and [`vite.config.js`](https://github.com/troncali/nest-vue/blob/main/apps/frontend/vite.config.ts).

**Comment by avimehenwal** [comment]
It's been sometime and I see there are so many people who want vue3 support (including myself). Kindly make it happen

**Comment by jamesray** [comment]
+1 for Vite + Vue3 + Nuxt3 support timeline if possible :)

**Comment by fabbaumgartner** [comment]
+1 for @nrwl/vue
